<?php

/**
 * Implements of hook_views_data().
 * Run hook_views_data for active CiviCRM components
 * 
 * https://civicrm.stackexchange.com/questions/741/how-do-i-add-civicrm-activity-attachment-to-view
 */
function civicrm_views_civicrm_activity_files_views_data_alter(&$data){
    /*
     * Add support for CiviCRM attachments
     */
    /*
     * Add CiviCRM file table
     */  
    $data['civicrm_file']['table']['group'] = t('CiviCRM Files');

    $data['civicrm_file']['table']['base'] = array(
      // 
      'field' => 'id',
      'title' => t('CiviCRM Files'),
      'help' => t("View displays CiviCRM Attachments"),
    );
    //Numeric File ID
    $data['civicrm_file']['id'] = array(
      'title' => t('File ID'),
      'help' => t('The numeric ID of the Attachment'),
      'field' => array(
        'handler' => 'views_handler_field_numeric',
        'click sortable' => TRUE,
      ),
      'argument' => array(
        'handler' => 'views_handler_argument_numeric',
        'numeric' => TRUE,
      ),
      'filter' => array(
        'handler' => 'views_handler_filter_numeric',
      ),
      'sort' => array(
        'handler' => 'views_handler_sort',
      ),
    );
      //URI
    $data['civicrm_file']['uri'] = array(
      'title' => t('URI'),
      'help' => t('The URI of the Attachment'),
      'field' => array(
        'handler' => 'views_handler_field_file',
        'click sortable' => TRUE,
      ),
    );
    //File Upload Date
    $data['civicrm_file']['upload_date'] = array(
      'title' => t('File Upload Date'),
      'help' => t('The date the Attachment was uploaded'),
      'field' => array(
        'handler' => 'civicrm_handler_field_datetime',
        'click sortable' => TRUE,
      ),
      'filter' => array(
        'handler' => 'civicrm_handler_filter_datetime',
      ),
      'sort' => array(
        'handler' => 'civicrm_handler_sort_date',
      ),
    );
    //File Description
    $data['civicrm_file']['description'] = array(
      'title' => t('Description'),
      'help' => t('The description of the Attachment'),
      'field' => array(
        'handler' => 'civicrm_handler_field',
        'click sortable' => TRUE,
      ),
      'argument' => array(
        'handler' => 'views_handler_argument_string',
        'numeric' => TRUE,
      ),
      'filter' => array(
        'handler' => 'views_handler_filter_string',
      ),
      'sort' => array(
        'handler' => 'views_handler_sort',
      ),
    );
    //File Mime Type
    $data['civicrm_file']['mime_type'] = array(
      'title' => t('Mime Type'),
      'help' => t('The mime type of the Attachment'),
      'field' => array(
      'handler' => 'views_handler_field_file_filemime',
      'click sortable' => TRUE,
     ),
   );


    /*
    //TABLE JOINS FOR CIVICRM ACTIVITIES GO HERE!
    /*
     * Add joins for CiviCRM attachments
     */
    $data['civicrm_file']['table']['join']['civicrm_activity'] = array(
      'left_table' => 'civicrm_entity_file',
      'left_field' => 'file_id',
      'field' => 'id',
    );

    $data['civicrm_entity_file']['table']['join']['civicrm_activity'] = array(
      // Directly links to file table
      'left_field' => 'id',
      'field' => 'entity_id',
      'extra' => array(
        array(
          'field' => 'entity_table',
          'value' => 'civicrm_activity',
          'numeric' => FALSE,
        ),
      ),
    );
}

